config/routes.rb
TestApp::Application.routes.draw do

  get '/users/:user_id/locations/:id' => 'locations#show', :as => 'user_location'
  post '/users/:user_id/locations/' => 'locations#create', :as => 'create_user_location'
  delete '/users/:user_id/locations/:id' => 'locations#destroy', :as => 'destroy_location'

  get 'users/:user_id' => 'users#show', :as => 'user'
  get 'users/new' => 'users#new', :as => 'new_user'
  get 'users/:user_id/edit' => 'users#edit', :as => 'edit_user'
  post 'users' => 'users#create'
  put 'users/:user_id' => 'users#update'
  delete 'users/:user_id' =>'users#destroy'
  
  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  root to: 'sessions#new'

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :user_id
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation
  validates :username, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # before_filter :check_session

  protected

  def check_session
  	unless User.find_by_id(session[:user_id])
  		redirect_to login_url, notice: "Please log in to use app."
  	end
  end
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
 
  # GET /locations/1
  # GET /locations/1.json
  def show
    @saved_locations = Location.find_all_by_user_id(params[:user_id])
    @user = User.find_by_id(params[:user_id])
    
    @location = Location.find(params[:id])
    media = Instagram.media_search(@location.latitude.to_s, @location.longitude.to_s)
    @pictures = media.data

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(:address => params[:address], :user_id => params[:user_id])    

    respond_to do |format|
       if @location.save
        format.html { redirect_to user_location_path( @location.user_id , @location.id), notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
       else
         format.html { redirect_to user_path, notice: "The location could not be created." }
         format.json { render json: @location.errors, status: :unprocessable_entity }
       end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to user_path }
      format.json { head :no_content }
    end
  end


  # # GET /locations
  # # GET /locations.json
  # def index
  #   @locations = Location.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @locations }
  #   end
  # end

  # GET /locations/new
  # GET /locations/new.json
  # def new
  #   @location = Location.new
  #   @users = User.all

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @location }
  #   end
  # end

  # # GET /locations/1/edit
  # def edit
  #   @location = Location.find(params[:id])
  # end

 

  # PUT /locations/1
  # PUT /locations/1.json
  # def update
  #   @location = Location.find(params[:id])

  #   respond_to do |format|
  #     if @location.update_attributes(params[:location])
  #       format.html { redirect_to @location, notice: 'Location was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @location.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by_username(params[:username])
  	if user and user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to user_path(user.id)
    else  		
      redirect_to login_path, alert: "Invalid user/password combination"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to login_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users/1
  # GET /users/1.json
  
  def show
    @user = User.find(params[:user_id])
    @saved_locations = Location.find_all_by_user_id(params[:user_id])
    @location = Location.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:user_id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_url,
          notice: "User #{@user.username} was successfully created. Now please log in." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:user_id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to user_url,
          notice: "User #{@user.username} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:user_id])
    @user.destroy
    session[:user_id] = nil

    respond_to do |format|
      format.html { redirect_to login_url }
      format.json { head :no_content }
    end
  end
end


  # GET /users
  # GET /users.json
  # def index
  #   @users = User.order(:username)

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @users }
  #   end
  # end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Amazing Instagram GeoSearch App | Built By Max Miller</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
	<div id="user_nav">
	<% if session[:user_id] %>
	<% user = User.find(session[:user_id]) %>
		You are logged in as <%= user.username %>. 
		<%= link_to 'Edit Account', edit_user_path %>
		<%= link_to 'Logout', logout_path, method: :delete %>
	<% end %>
	</div>
	<%= yield %>
</div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <legend>Where would you like to search?</legend>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.address %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
    <td><%= location.user_id %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<div id="side">
<p>
  <b>Saved Locations:</b>
  <ul>
    <% @saved_locations.each do |l| %>
    <li><%= link_to l.address, user_location_path(@user, l.id) %></li>
    <% end %>
  </ul>
  <%= link_to 'Back', user_path(@user) %>
</p>
</div>



<div id="main">
<h2><%= @location.address %> | <%= link_to 'Delete Location', destroy_location_path(@location.user_id, @location), method: :delete, data: { confirm: 'Are you sure?' } %></h2>
	<% @pictures.each do |pic| %>
	<div id="picture"><%= image_tag pic.images.low_resolution.url %></div>
	<% end %>
</div>

app/views/users/_form.html.erb
<div class="form">

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter User Details</legend>
 
  <div class="field">
    <%= f.label :username %><br />:
    <%= f.text_field :username, size: 40 %>
  </div>
  
  <div class="field">
    <%= f.label :password, 'Password' %><br />:
    <%= f.password_field :password, size: 40 %>
  </div>
  
  <div class="field">
    <%= f.label :password_confirmation, 'Confirm' %><br />:
    <%= f.password_field :password_confirmation, size: 40 %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/users/_search_form.html.erb
<%= form_tag create_user_location_path(@user) do %>

<fieldset>
  <legend>Where would you like to search?</legend>
  <div class="field">
    <%= label_tag :address %><br />
    <%= text_field_tag :address %>
  </div>
  
  <div class="actions">
    <%= submit_tag "Create Location" %>
  </div>
</fieldset>

<% end %>

app/views/users/edit.html.erb
<h1><%= @user.username %>'s Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/users/index.html.erb
<h1>Listing users</h1>
  <% if notice %>
  <p id="notice"><%= notice %></p>
  <% end %>
<table>
  <tr>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="side">
<p>
  <b>Saved Locations:</b>
  <ul>
  	<% @saved_locations.each do |l| %>
  	<li><%= link_to l.address, user_location_path(@user, l.id) %></li>
  	<% end %>
  </ul>
</p>
</div>

<div id="main">
<h2>Welcome <%= @user.username %>!</h2>
<%= render 'search_form' %>
</div>